[config]

[config.wallpaper]
# Whether to set the wallpaper or not
set = false

# The base command to run for applying the wallpaper.
# Keywords like {{ image }} or anything that works inside of hooks works here.
# You could also set a static color if you use the color keywords and the wallpaper setter supports it.
command = "awww img --transition-type wipe {{ image }}"

# For example, killing the wallpaper daemon. Usage is like a normal hook.
# pre_hook = ""

[templates.waybar]
input_path = '~/.config/matugen/colors.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'

[templates.mako]
input_path = '~/.config/matugen/mako'
output_path = '~/.config/mako/colors'
post_hook = 'makoctl reload'

[templates.wezterm]
input_path = '~/.config/matugen/wezterm_theme.toml'
output_path = '~/.config/wezterm/colors/matugen_theme.toml'
post_hook = 'touch ~/.config/wezterm/wezterm.lua'

[templates.foot]
input_path = '~/.config/matugen/foot-colors.ini'
output_path = '~/.config/matugen/generated/foot-colors.ini'
post_hook = '''
  pkill -SIGUSR1 foot
  ln -nfs "$HOME/.config/matugen/generated/foot-colors.ini" "$HOME/.config/foot/foot-colors.ini"
  touch "$HOME/.config/foot/foot.ini" || :
'''

[templates.fuzzel]
input_path = '~/.config/matugen/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'

[templates.zellij]
input_path = '~/.config/matugen/zellij-theme.kdl.tera'
output_path = '~/.config/zellij/themes/matugen.kdl'

# Add this line to get hot-reloading. Without it, the new theme will only
# appear on next start
post_hook = 'touch ~/.config/zellij/config.kdl'
