"$schema" = 'https://starship.rs/config-schema.json'

format = "$all"
right_format = "${custom.timewarrior}"

# Custom Timewarrior module
[custom.timewarrior]
command = "~/scripts/timew_status.sh"
when = "true"
shell = ["bash", "--noprofile", "--norc"]
format = " [$output]($style)"
style = "bold green"
