#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

# A bash script to create daily notes
# What i need this script to do:
# - Run with no arguments
# - take todays day and see if file already exists
#   - If not exists, create file and drop me into editor (Nvim)
#   - If file exist, crop me into editor (nvim)
# - If new file is created, copy todo's from last daily note into new one.
# Running examples:
# daily

today=$(date +"%Y%m%d")
dailypath="$SECOND_BRAIN/daily"

newnote=$(cat <<EOF
---
date: $(date +"%Y-%m-%d")
tag:
- daily
---

# Agenda

# Todo

# Notes

## links

EOF)

newest_daily(){

}

open_file() {
  if [-e "$daily/$today.md"]; then
    nvim "$dailypath/$today.md"
  else
    # Sets up timestamp to use later
    timestamp=$(date +"%Y-%m-%d")
    
    # CD into daily path
    cd "$dailypath"

    # Create daily file
    touch $today.md

    
}
